### ISSUE TITLE
Remove 'Download Generator' from App version

### ISSUE THREAD

**Issue by ro-savage** [Encrypt-S/paper-wallet#9]
Currently, when you open the app version, it shows you a link to download the app again.

Lets hide this if we can on the app version.

![image](https://user-images.githubusercontent.com/9244507/38317753-2697b15c-3871-11e8-8d6a-b919a75bc952.png)

**Comment by matt-auckland** [comment]
What a coincidence, I was planning on adding this feature already 🙂

**Comment by matt-auckland** [comment]
Fixed #10
